=== SoBrodacious/NondescriptRenderingApp/NondescriptRenderApp/GraphicsApp/ShapeDefinitions/Ellipse.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Ellipse"
    targetNamespace="http://tempuri.org/Ellipse.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/Ellipse.xsd"
    xmlns:mstns="http://tempuri.org/Ellipse.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="ellipse" type="ellipseType" />

  <xs:complexType name="ellipseType">
    <xs:all>
      <xs:element name="ellipseName" type="xs:string" />
      <xs:element name="dimensions" type="dimensionsType" />
      <xs:element name="strokeWeight">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="strokeColor" type="colorType" />
      <xs:element name="fillColor" type="colorType" />
    </xs:all>
  </xs:complexType>

  <!-- Point -->
  <xs:complexType name="pointType">
    <xs:all>
      <xs:element name="x" type="xs:double" />
      <xs:element name="y" type="xs:double" />
    </xs:all>
  </xs:complexType>
  
  <!-- Dimensions -->
  <xs:complexType name="dimensionsType">
    <xs:all>
      <xs:element name="width" type="xs:double" />
      <xs:element name="height" type="xs:double" />
    </xs:all>
  </xs:complexType>

  <!-- Color -->
  <xs:complexType name="colorType">
    <xs:all>
      <xs:element name="r">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="255" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="g">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="255" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="b">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="255" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
  </xs:complexType>


</xs:schema>

=== SoBrodacious/NondescriptRenderingApp/NondescriptRenderApp/GraphicsApp/bin/Release/netcoreapp3.1/win-x86/ShapeDefinitions/WideCircle.xml
<?xml version="1.0" encoding="utf-8" ?>

<ellipse
  xmlns="http://tempuri.org/Ellipse.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://tempuri.org/Ellipse.xsd Ellipse.xsd"
  >
  <ellipseName>Circle</ellipseName>
  <dimensions>
    <width>60</width>
    <height>30</height>
  </dimensions>
  <strokeWeight>3</strokeWeight>
  <strokeColor>
    <r>0</r>
    <g>0</g>
    <b>0</b>
  </strokeColor>
  <fillColor>
    <r>180</r>
    <g>60</g>
    <b>180</b>
  </fillColor>
</ellipse>
